GET {{baseUrl}}/Students
accept: application/json;odata.metadata=full
# If-Modified-Since: Thu, 12 Dec 2024 01:32:46 GMT

###

GET {{baseUrl}}/Students?$select=DateOfBirth,FirstName,LastName&orderby=DateOfBirth
accept: application/json;odata.metadata=full

###

GET {{baseUrl}}/Students?$filter=LastName eq 'Tailor'
accept: application/json;odata.metadata=full

###
GET {{baseUrl}}/Students(2342506579)
accept: application/json;odata.metadata=full

###

GET {{baseUrl}}/Students(2342506579)/group
accept: application/json;odata.metadata=full

###

POST {{baseUrl}}/Students(1)/Group(2)/$ref
accept: application/json;odata.metadata=full

###

POST {{baseUrl}}/Students(2342506579)/Group/$ref
Content-Type: application/json
accept: application/json;odata.metadata=full

{
    "@odata.id": "http://localhost:5139/Groups(1923003551)"
}
###

DELETE {{baseUrl}}/Students(2342506579)/Group/$ref
accept: application/json;odata.metadata=full

###

OPTIONS  {{baseUrl}}/Students(1)/Group(2)/$ref

###

POST {{baseUrl}}/Students
content-type: application/json

{
    "Id": 19267897,
    "FirstName": "Abraham",
    "LastName": "Shoeperson",
    "DateOfBirth": "1999-01-01",
    "Email": "as@random-tu.de",
    "GroupId": 1923003579,
    "Group": null
}

###

PUT {{baseUrl}}/Students(19267897)
content-type: application/json

{
    "Id": 19267897,
    "FirstName": "Abraham Lincoln",
    "LastName": "Randuin",
    "DateOfBirth": "1999-01-01",
    "Email": "alr@random-tu.de",
    "GroupId": 1923003579,
    "Group": null
}

###

DELETE {{baseUrl}}/Students(19267897)

###

GET http://localhost:5139/$metadata#Students