GET {{baseUrl}}/Students
accept: application/json;odata.metadata=full

###

GET {{baseUrl}}/Students?$orderby=DateOfBirth
accept: application/json;odata.metadata=full

###


GET {{baseUrl}}/Students(4)
accept: application/json;odata.metadata=full

###

GET {{baseUrl}}/Students(4)/group
accept: application/json;odata.metadata=full

###

POST {{baseUrl}}/Students(1)/Group(2)/$ref
accept: application/json;odata.metadata=full

###

POST {{baseUrl}}/Students(4)/Group/$ref
Content-Type: application/json
accept: application/json;odata.metadata=full

{
    "@odata.id": "http://localhost:5139/Groups(2)"
}
###

DELETE {{baseUrl}}/Students(1)/Group/$ref
accept: application/json;odata.metadata=full

###

OPTIONS  {{baseUrl}}/Students(1)/Group(2)/$ref

###

POST {{baseUrl}}/Students
content-type: application/json

{
    "Id": 8,
    "FirstName": "Abraham",
    "LastName": "Shoeperson",
    "DateOfBirth": "1999-01-01",
    "Email": "as@random-tu.de",
    "GroupId": 1,
    "Group": null
}

###

PUT {{baseUrl}}/Students(4)
content-type: application/json

{
    "Id": 1,
    "FirstName": "Abraham Lincoln",
    "LastName": "Randuin",
    "DateOfBirth": "1999-01-01",
    "Email": "alr@random-tu.de",
    "GroupId": 2,
    "Group": null
}

###


GET http://localhost:5139/$metadata#Students